### ISSUE TITLE
Host name `pinba_server`

### ISSUE THREAD

**Issue by sempasha** [Sannis/node-pinba#6]
Using host name as `pinba_server` causes name resolving while sending Pinba packet to Pinba server. Most time you deal with single Pinba server. If you need to send many Pinba packets to track your clients activity you also need resolve Pinba server host name so many times. As a result, you can get something like DNS Flood, not really but essence is the same. Ore some other troubles.

For example, today I found messages in system logs:
```
docker[6335]: time="2017-09-28T06:25:05.427666901+05:00" level=warning msg="Connect failed: dial udp 172.16.8.8:53: connect: resource temporarily unavailable"
```
It says docker cannot connect to DNS server, i.e. docker cannot resolve some host name. It may caused by docker resolver issues, but the reason is high Pinba requests frequency.

I think it would be nice to have some kind of DNS cache in the library to avoid such situation. What you think about?

**Comment by Sannis** [comment]
@sempasha, agreed, DNS resove should be cached for some time.

**Comment by sempasha** [comment]
Have you any plans to publish this update at npm registry?

**Comment by Sannis** [comment]
@sempasha planning to do this in few days.
